name: WinGet Manifests

on:
  push:
  schedule:
    - cron: "0 * * * *"

permissions: write-all

jobs:
  run:
    name: Parse WinGet Manifests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup install stable

      - name: Build
        run: |
          git clone https://github.com/microsoft/winget-pkgs.git
          cargo run --release

      - name: Upload
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update win32 repo"
          push: true
          committer_name: Actions Bot
          committer_email: actions@github.com
